<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  vc:minVersion="1.1">

  <xs:include schemaLocation="hevc_common.xsd"/>
  
  <xs:element name="HEVCBitstream">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NALUnit" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="uri" type="xs:anyURI"/>

      <xs:assert test="exists(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_progressive_source_flag)"/>
      <xs:assert test="string(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_progressive_source_flag) = '1'"/>
      <xs:assert test="exists(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_interlaced_source_flag)"/>
      <xs:assert test="string(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_interlaced_source_flag) = '0'"/>
      <xs:assert test="exists(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_non_packed_constraint_flag)"/>
      <xs:assert test="string(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_non_packed_constraint_flag) = '1'"/>
      <xs:assert test="exists(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_frame_only_constraint_flag)"/>
      <xs:assert test="string(NALUnit[nuh_layer_id=0]/SequenceParameterSet/general_frame_only_constraint_flag) = '1'"/>
    </xs:complexType>
  </xs:element>

</xs:schema>
