<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  vc:minVersion="1.1">

  <xs:include schemaLocation="hevc_common.xsd"/>
  
  <xs:element name="HEVCBitstream">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NALUnit" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="uri" type="xs:anyURI"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet)"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet/vps_num_layer_sets_minus1)"/>
      <xs:assert test="NALUnit/VideoParameterSet/vps_num_layer_sets_minus1 >= 1"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet/layer_id_included_flag[@i=1][@j=0])"/>
      <xs:assert test="NALUnit/VideoParameterSet/layer_id_included_flag[@i=1][@j=0] = 1"/>
      <xs:assert test="exists(NALUnit/VideoParameterSet/layer_id_included_flag[@i=1][@j > 0][. = 1])"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet/scalability_mask_flag[@i=1])"/>
      <xs:assert test="NALUnit/VideoParameterSet/scalability_mask_flag[@i=1] = 1"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet/InternalVariables/ScalabilityId[@i=1][@j=1])"/>
      <xs:assert test="NALUnit/VideoParameterSet/InternalVariables/ScalabilityId[@i=1][@j=1] = 1"/>

      <xs:assert test="exists(NALUnit/VideoParameterSet/default_output_layer_idc)"/>
      <xs:assert test="NALUnit/VideoParameterSet/default_output_layer_idc = 0"/>

      <xs:assert test="exists(NALUnit/SequenceParameterSet/chroma_format_idc)"/>
      <xs:assert test="NALUnit/SequenceParameterSet/chroma_format_idc = 1"/>

      <xs:assert test="exists(NALUnit/SequenceParameterSet/aspect_ratio_idc)"/>
      <xs:assert test="NALUnit/SequenceParameterSet/aspect_ratio_idc = 1"/>

      <xs:assert test="
        (
          exists(NALUnit/SequenceParameterSet/colour_primaries) and
          NALUnit/SequenceParameterSet/colour_primaries = 1 and
          exists(NALUnit/SequenceParameterSet/transfer_characteristics) and
          NALUnit/SequenceParameterSet/transfer_characteristics = 1 and
          exists(NALUnit/SequenceParameterSet/matrix_coeffs) and
          NALUnit/SequenceParameterSet/matrix_coeffs = 1 and
          exists(NALUnit/SequenceParameterSet/chroma_sample_loc_type_top_field) and
          NALUnit/SequenceParameterSet/chroma_sample_loc_type_top_field = 0
        )
        or
        (
          exists(NALUnit/SequenceParameterSet/colour_primaries) and
          NALUnit/SequenceParameterSet/colour_primaries = 9 and
          exists(NALUnit/SequenceParameterSet/transfer_characteristics) and
          (
            NALUnit/SequenceParameterSet/transfer_characteristics = 14 or
            NALUnit/SequenceParameterSet/transfer_characteristics = 16 or
            NALUnit/SequenceParameterSet/transfer_characteristics = 18
          ) and
          exists(NALUnit/SequenceParameterSet/matrix_coeffs) and
          NALUnit/SequenceParameterSet/matrix_coeffs = 9 and
          exists(NALUnit/SequenceParameterSet/chroma_sample_loc_type_top_field) and
          NALUnit/SequenceParameterSet/chroma_sample_loc_type_top_field = 2
        )
      "/>

      <xs:assert test="exists(NALUnit/SEI/SEIMessage/payload/three_dimensional_reference_displays_info)"/>

      <xs:assert test="NALUnit/SEI/SEIMessage/payload/three_dimensional_reference_displays_info/num_ref_displays_minus1 = 0"/>

      <xs:assert test="every $left_view in NALUnit/SEI/SEIMessage/payload/three_dimensional_reference_displays_info/left_view_id
                    satisfies $left_view = NALUnit/VideoParameterSet/view_id_val[@i = $left_view/@i]"/>

      <xs:assert test="every $right_view in NALUnit/SEI/SEIMessage/payload/three_dimensional_reference_displays_info/right_view_id
                    satisfies $right_view = NALUnit/VideoParameterSet/view_id_val[@i = number($right_view/@i) + 1] and
                    $right_view != NALUnit/SEI/SEIMessage/payload/three_dimensional_reference_displays_info/left_view_id[@i = $right_view/@i]"/>

    </xs:complexType>
  </xs:element>

</xs:schema>
