<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  vc:minVersion="1.1">

  <!-- Require HEVC bitstream schema -->
  <xs:include schemaLocation="hevc_common.xsd"/>
  
  <xs:element name="HEVCBitstream">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NALUnit" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="uri" type="xs:anyURI"/>
      <!-- TODO: 3GPP Stereoscopic format -->

      <!-- MV-HEVC-Dual-layers-UHD420-Dec -->
      <!-- HEVC Progressive constraints -->
      <xs:assert test="exists(NALUnit/SequenceParameterSet/general_progressive_source_flag)"/>
      <xs:assert test="string(NALUnit/SequenceParameterSet/general_progressive_source_flag) = '1'"/>
      <xs:assert test="exists(NALUnit/SequenceParameterSet/general_interlaced_source_flag)"/>
      <xs:assert test="string(NALUnit/SequenceParameterSet/general_interlaced_source_flag) = '0'"/>
      <xs:assert test="exists(NALUnit/SequenceParameterSet/general_non_packed_constraint_flag)"/>
      <xs:assert test="string(NALUnit/SequenceParameterSet/general_non_packed_constraint_flag) = '1'"/>
      <xs:assert test="exists(NALUnit/SequenceParameterSet/general_frame_only_constraint_flag)"/>
      <xs:assert test="string(NALUnit/SequenceParameterSet/general_frame_only_constraint_flag) = '1'"/>
      <!-- TODO:HEVC VUI constraints -->

      <!-- Remainder of MV-HEVC Stereo Operation Point -->
      <xs:assert test="exists(NALUnit/VideoParameterSet)"/>
      <xs:assert test="exists(NALUnit/VideoParameterSet/vps_max_layers_minus1)"/>
      <xs:assert test="NALUnit/VideoParameterSet/vps_max_layers_minus1 = 1"/>
      <xs:assert test="exists(NALUnit/SequenceParameterSet/chroma_format_idc)"/>
      <xs:assert test="NALUnit/SequenceParameterSet/chroma_format_idc = 1"/>
      <xs:assert test="exists(NALUnit/SequenceParameterSet/aspect_ratio_idc)"/>
      <xs:assert test="NALUnit/SequenceParameterSet/aspect_ratio_idc = 1"/>
      <!-- TODO: More todos -->
    </xs:complexType>
  </xs:element>

</xs:schema>
